export const menuList = [{
    'createTime': '2019-12-04 09:42:20',
    'updateTime': '2019-12-16 10:09:58',
    'creator': 'admin/admin',
    'updator': 'admin/admin',
    'menuId': 13136,
    'parentId': 0,
    'name': '公共基础类维护',
    'url': 'common-base',
    'perms': 'base:dictionary:menu:hospital',
    'type': 0,
    'icon': null,
    'orderNum': 3000,
    'deleteFlag': 2,
    'syncTime': '9999-01-01',
    'menuOrgType': 'HOSPITAL',
    'typeDicName': null,
    'menuOrgTypeDicName': null,
    'parentName': null,
    'open': null,
    'list': [{
        'createTime': '2019-12-04 09:52:39',
        'updateTime': '2020-01-03 11:44:57',
        'creator': 'admin/admin',
        'updator': 'admin/admin',
        'menuId': 13142,
        'parentId': 13136,
        'name': '系统参数维护',
        'url': 'common-base/parameter/index',
        'perms': 'sys:config:menu:hospital',
        'type': 1,
        'icon': null,
        'orderNum': 100,
        'deleteFlag': 2,
        'syncTime': '9999-01-01',
        'menuOrgType': 'HOSPITAL',
        'typeDicName': null,
        'menuOrgTypeDicName': null,
        'parentName': null,
        'open': null,
        'list': null
    }, {
        'createTime': '2019-12-04 09:53:11',
        'updateTime': '2020-01-03 11:45:09',
        'creator': 'admin/admin',
        'updator': 'admin/admin',
        'menuId': 13143,
        'parentId': 13136,
        'name': '基本表维护',
        'url': 'common-base/base-table/index',
        'perms': 'base:dictionary:menu:hospital',
        'type': 1,
        'icon': null,
        'orderNum': 110,
        'deleteFlag': 2,
        'syncTime': '9999-01-01',
        'menuOrgType': 'HOSPITAL',
        'typeDicName': null,
        'menuOrgTypeDicName': null,
        'parentName': null,
        'open': null,
        'list': null
    }]
    }, {
    'createTime': '2019-11-29 16:30:41',
    'updateTime': '2019-12-16 10:09:35',
    'creator': 'admin/admin',
    'updator': 'admin/admin',
    'menuId': 12894,
    'parentId': 0,
    'name': '系统管理',
    'url': 'system',
    'perms': 'system',
    'type': 0,
    'icon': null,
    'orderNum': 3200,
    'deleteFlag': 2,
    'syncTime': '9999-01-01',
    'menuOrgType': 'HOSPITAL',
    'typeDicName': null,
    'menuOrgTypeDicName': null,
    'parentName': null,
    'open': null,
    'list': [{
        'createTime': '2019-12-04 09:40:45',
        'updateTime': '2019-12-16 10:09:06',
        'creator': 'admin/admin',
        'updator': 'admin/admin',
        'menuId': 13133,
        'parentId': 12894,
        'name': '系统登录用户',
        'url': 'system/user',
        'perms': 'sys:user:menu:hospital',
        'type': 1,
        'icon': 'admin',
        'orderNum': 0,
        'deleteFlag': 2,
        'syncTime': '9999-01-01',
        'menuOrgType': 'HOSPITAL',
        'typeDicName': null,
        'menuOrgTypeDicName': null,
        'parentName': null,
        'open': null,
        'list': null
    }]
    }
]
