export const menuList = [{
    "createTime": "2019-12-04 09:42:20",
    "updateTime": "2019-12-16 10:09:58",
    "creator": "admin/admin",
    "updator": "admin/admin",
    "menuId": 13136,
    "parentId": 0,
    "name": "公共基础类维护",
    "url": "common-base",
    "perms": "base:dictionary:menu:hospital",
    "type": 0,
    "icon": null,
    "orderNum": 3000,
    "deleteFlag": 2,
    "syncTime": "9999-01-01",
    "menuOrgType": "HOSPITAL",
    "typeDicName": null,
    "menuOrgTypeDicName": null,
    "parentName": null,
    "open": null,
    "list": [{
        "createTime": "2019-12-04 09:52:39",
        "updateTime": "2020-01-03 11:44:57",
        "creator": "admin/admin",
        "updator": "admin/admin",
        "menuId": 13142,
        "parentId": 13136,
        "name": "系统参数维护",
        "url": "common-base/parameter/index",
        "perms": "sys:config:menu:hospital",
        "type": 1,
        "icon": null,
        "orderNum": 100,
        "deleteFlag": 2,
        "syncTime": "9999-01-01",
        "menuOrgType": "HOSPITAL",
        "typeDicName": null,
        "menuOrgTypeDicName": null,
        "parentName": null,
        "open": null,
        "list": null
    }, {
        "createTime": "2019-12-04 09:53:11",
        "updateTime": "2020-01-03 11:45:09",
        "creator": "admin/admin",
        "updator": "admin/admin",
        "menuId": 13143,
        "parentId": 13136,
        "name": "基本表维护",
        "url": "common-base/base-table/index",
        "perms": "base:dictionary:menu:hospital",
        "type": 1,
        "icon": null,
        "orderNum": 110,
        "deleteFlag": 2,
        "syncTime": "9999-01-01",
        "menuOrgType": "HOSPITAL",
        "typeDicName": null,
        "menuOrgTypeDicName": null,
        "parentName": null,
        "open": null,
        "list": null
    }]
}, {
    "createTime": "2019-11-29 16:30:41",
    "updateTime": "2019-12-16 10:09:35",
    "creator": "admin/admin",
    "updator": "admin/admin",
    "menuId": 12894,
    "parentId": 0,
    "name": "系统管理",
    "url": "system",
    "perms": "system",
    "type": 0,
    "icon": null,
    "orderNum": 3200,
    "deleteFlag": 2,
    "syncTime": "9999-01-01",
    "menuOrgType": "HOSPITAL",
    "typeDicName": null,
    "menuOrgTypeDicName": null,
    "parentName": null,
    "open": null,
    "list": [{
        "createTime": "2019-12-04 09:40:45",
        "updateTime": "2019-12-16 10:09:06",
        "creator": "admin/admin",
        "updator": "admin/admin",
        "menuId": 13133,
        "parentId": 12894,
        "name": "系统登录用户",
        "url": "system/user",
        "perms": "sys:user:menu:hospital",
        "type": 1,
        "icon": "admin",
        "orderNum": 0,
        "deleteFlag": 2,
        "syncTime": "9999-01-01",
        "menuOrgType": "HOSPITAL",
        "typeDicName": null,
        "menuOrgTypeDicName": null,
        "parentName": null,
        "open": null,
        "list": null
    }]
}, {
    "createTime": "2019-12-04 09:42:06",
    "updateTime": "2019-12-16 10:09:50",
    "creator": "admin/admin",
    "updator": "admin/admin",
    "menuId": 13135,
    "parentId": 0,
    "name": "组织架构类维护",
    "url": "system-maintain",
    "perms": "sys:zuzhi:menu::hospital",
    "type": 0,
    "icon": null,
    "orderNum": 3400,
    "deleteFlag": 2,
    "syncTime": "9999-01-01",
    "menuOrgType": "HOSPITAL",
    "typeDicName": null,
    "menuOrgTypeDicName": null,
    "parentName": null,
    "open": null,
    "list": [{
        "createTime": "2019-12-04 09:49:11",
        "updateTime": "2019-12-19 11:43:42",
        "creator": "admin/admin",
        "updator": "admin/admin",
        "menuId": 13137,
        "parentId": 13135,
        "name": "机构维护",
        "url": "system-maintain/organization/index",
        "perms": "base:org:menu:hospital",
        "type": 1,
        "icon": null,
        "orderNum": 100,
        "deleteFlag": 2,
        "syncTime": "9999-01-01",
        "menuOrgType": "HOSPITAL",
        "typeDicName": null,
        "menuOrgTypeDicName": null,
        "parentName": null,
        "open": null,
        "list": null
    }, {
        "createTime": "2019-12-04 09:49:41",
        "updateTime": "2019-12-04 09:49:41",
        "creator": "admin/admin",
        "updator": "admin/admin",
        "menuId": 13138,
        "parentId": 13135,
        "name": "科室维护",
        "url": "system-maintain/department/index",
        "perms": "base:subject:menu:hospital",
        "type": 1,
        "icon": null,
        "orderNum": 110,
        "deleteFlag": 2,
        "syncTime": "9999-01-01",
        "menuOrgType": "HOSPITAL",
        "typeDicName": null,
        "menuOrgTypeDicName": null,
        "parentName": null,
        "open": null,
        "list": null
    }, {
        "createTime": "2019-12-04 09:50:12",
        "updateTime": "2019-12-04 09:50:12",
        "creator": "admin/admin",
        "updator": "admin/admin",
        "menuId": 13139,
        "parentId": 13135,
        "name": "角色维护",
        "url": "system-maintain/role/index",
        "perms": "sys:role:menu:hospital",
        "type": 1,
        "icon": null,
        "orderNum": 120,
        "deleteFlag": 2,
        "syncTime": "9999-01-01",
        "menuOrgType": "HOSPITAL",
        "typeDicName": null,
        "menuOrgTypeDicName": null,
        "parentName": null,
        "open": null,
        "list": null
    }, {
        "createTime": "2019-12-04 09:50:47",
        "updateTime": "2019-12-04 09:50:47",
        "creator": "admin/admin",
        "updator": "admin/admin",
        "menuId": 13140,
        "parentId": 13135,
        "name": "人员维护",
        "url": "system-maintain/personnel/index",
        "perms": "base:businessuser:menu:hospital",
        "type": 1,
        "icon": null,
        "orderNum": 130,
        "deleteFlag": 2,
        "syncTime": "9999-01-01",
        "menuOrgType": "HOSPITAL",
        "typeDicName": null,
        "menuOrgTypeDicName": null,
        "parentName": null,
        "open": null,
        "list": null
    }, {
        "createTime": "2019-12-04 09:51:20",
        "updateTime": "2019-12-04 09:51:20",
        "creator": "admin/admin",
        "updator": "admin/admin",
        "menuId": 13141,
        "parentId": 13135,
        "name": "权限维护",
        "url": "system-maintain/authority/index",
        "perms": "sys:userright:menu:hospital",
        "type": 1,
        "icon": null,
        "orderNum": 140,
        "deleteFlag": 2,
        "syncTime": "9999-01-01",
        "menuOrgType": "HOSPITAL",
        "typeDicName": null,
        "menuOrgTypeDicName": null,
        "parentName": null,
        "open": null,
        "list": null
    }]
}, {
    "createTime": "2019-12-09 17:08:49",
    "updateTime": "2019-12-16 10:09:43",
    "creator": "admin/admin",
    "updator": "admin/admin",
    "menuId": 13429,
    "parentId": 0,
    "name": "药品类维护",
    "url": "hospital-drug-maintenance",
    "perms": "hospital-drug-maintenance",
    "type": 0,
    "icon": null,
    "orderNum": 3600,
    "deleteFlag": 2,
    "syncTime": "9999-01-01",
    "menuOrgType": "HOSPITAL",
    "typeDicName": null,
    "menuOrgTypeDicName": null,
    "parentName": null,
    "open": null,
    "list": [{
        "createTime": "2019-12-09 17:10:54",
        "updateTime": "2019-12-18 14:45:29",
        "creator": "admin/admin",
        "updator": "admin/admin",
        "menuId": 13430,
        "parentId": 13429,
        "name": "药品分类维护",
        "url": "hospital-drug-maintenance/drugClassification/index",
        "perms": "base:hospitaldrugtype:menu:hospital",
        "type": 1,
        "icon": null,
        "orderNum": 100,
        "deleteFlag": 2,
        "syncTime": "9999-01-01",
        "menuOrgType": "HOSPITAL",
        "typeDicName": null,
        "menuOrgTypeDicName": null,
        "parentName": null,
        "open": null,
        "list": null
    }, {
        "createTime": "2019-12-09 17:11:30",
        "updateTime": "2019-12-09 17:11:30",
        "creator": "admin/admin",
        "updator": "admin/admin",
        "menuId": 13431,
        "parentId": 13429,
        "name": "药品维护",
        "url": "hospital-drug-maintenance/drug/index",
        "perms": "base:hospitaldrug:menu:hospital",
        "type": 1,
        "icon": null,
        "orderNum": 110,
        "deleteFlag": 2,
        "syncTime": "9999-01-01",
        "menuOrgType": "HOSPITAL",
        "typeDicName": null,
        "menuOrgTypeDicName": null,
        "parentName": null,
        "open": null,
        "list": null
    }]
}, {
    "createTime": "2019-12-09 17:18:27",
    "updateTime": "2019-12-16 10:10:05",
    "creator": "admin/admin",
    "updator": "admin/admin",
    "menuId": 13432,
    "parentId": 0,
    "name": "收费类维护",
    "url": "hospital-fee-maintain",
    "perms": "hospital-fee-maintain",
    "type": 0,
    "icon": null,
    "orderNum": 3800,
    "deleteFlag": 2,
    "syncTime": "9999-01-01",
    "menuOrgType": "HOSPITAL",
    "typeDicName": null,
    "menuOrgTypeDicName": null,
    "parentName": null,
    "open": null,
    "list": [{
        "createTime": "2019-12-11 19:12:40",
        "updateTime": "2019-12-16 10:06:53",
        "creator": "admin/admin",
        "updator": "admin/admin",
        "menuId": 16604,
        "parentId": 13432,
        "name": "费别维护",
        "url": "hospital-fee-maintain/feeType/index",
        "perms": "base:hospitalfeepay:menu",
        "type": 1,
        "icon": null,
        "orderNum": 100,
        "deleteFlag": 2,
        "syncTime": "9999-01-01",
        "menuOrgType": "HOSPITAL",
        "typeDicName": null,
        "menuOrgTypeDicName": null,
        "parentName": null,
        "open": null,
        "list": null
    }, {
        "createTime": "2019-12-11 18:51:11",
        "updateTime": "2019-12-19 14:05:54",
        "creator": "admin/admin",
        "updator": "admin/admin",
        "menuId": 13688,
        "parentId": 13432,
        "name": "附加项收费维护",
        "url": "hospital-fee-maintain/subjoinFee/index",
        "perms": "base:hospadditionalfeedetail:meun:hospital",
        "type": 1,
        "icon": null,
        "orderNum": 110,
        "deleteFlag": 2,
        "syncTime": "9999-01-01",
        "menuOrgType": "HOSPITAL",
        "typeDicName": null,
        "menuOrgTypeDicName": null,
        "parentName": null,
        "open": null,
        "list": null
    }, {
        "createTime": "2019-12-09 17:20:30",
        "updateTime": "2019-12-11 18:51:41",
        "creator": "admin/admin",
        "updator": "admin/admin",
        "menuId": 13433,
        "parentId": 13432,
        "name": "收费分类维护",
        "url": "hospital-fee-maintain/feeClass/index",
        "perms": "base:feetype:menu:hospital",
        "type": 1,
        "icon": null,
        "orderNum": 120,
        "deleteFlag": 2,
        "syncTime": "9999-01-01",
        "menuOrgType": "HOSPITAL",
        "typeDicName": null,
        "menuOrgTypeDicName": null,
        "parentName": null,
        "open": null,
        "list": null
    }, {
        "createTime": "2019-12-09 17:21:42",
        "updateTime": "2019-12-09 17:21:42",
        "creator": "admin/admin",
        "updator": "admin/admin",
        "menuId": 13434,
        "parentId": 13432,
        "name": "收费项目维护",
        "url": "hospital-fee-maintain/feeProject/index",
        "perms": "base:feeitem:menu:hospital",
        "type": 1,
        "icon": null,
        "orderNum": 130,
        "deleteFlag": 2,
        "syncTime": "9999-01-01",
        "menuOrgType": "HOSPITAL",
        "typeDicName": null,
        "menuOrgTypeDicName": null,
        "parentName": null,
        "open": null,
        "list": null
    }]
}, {
    "createTime": "2019-11-29 16:30:41",
    "updateTime": "2019-12-16 10:09:35",
    "creator": "admin/admin",
    "updator": "admin/admin",
    "menuId": 17098,
    "parentId": 0,
    "name": "诊疗项目类维护",
    "url": null,
    "perms": null,
    "type": 0,
    "icon": null,
    "orderNum": 4000,
    "deleteFlag": 2,
    "syncTime": "9999-01-01",
    "menuOrgType": "HOSPITAL",
    "typeDicName": null,
    "menuOrgTypeDicName": null,
    "parentName": null,
    "open": null,
    "list": [{
        "createTime": null,
        "updateTime": "2019-12-27 11:49:53",
        "creator": null,
        "updator": "admin/admin",
        "menuId": 17099,
        "parentId": 17098,
        "name": "诊疗项目分类维护",
        "url": "hospital-project-maintain/proClass/index",
        "perms": "base:hospitalclinictype:menu:hospital",
        "type": 1,
        "icon": null,
        "orderNum": 100,
        "deleteFlag": 2,
        "syncTime": "9999-01-01",
        "menuOrgType": "HOSPITAL",
        "typeDicName": null,
        "menuOrgTypeDicName": null,
        "parentName": null,
        "open": null,
        "list": null
    }, {
        "createTime": null,
        "updateTime": "2019-12-27 11:55:48",
        "creator": null,
        "updator": "admin/admin",
        "menuId": 17105,
        "parentId": 17098,
        "name": "诊疗项目维护",
        "url": "hospital-project-maintain/project/index",
        "perms": "base:hospitalclinicitem:menu:hospital",
        "type": 1,
        "icon": null,
        "orderNum": 110,
        "deleteFlag": 2,
        "syncTime": "9999-01-01",
        "menuOrgType": "HOSPITAL",
        "typeDicName": null,
        "menuOrgTypeDicName": null,
        "parentName": null,
        "open": null,
        "list": null
    }]
}, {
    "createTime": "2020-01-03 09:40:49",
    "updateTime": "2020-01-14 16:34:46",
    "creator": "yeyi/yeyi",
    "updator": "yeyi/yeyi",
    "menuId": 19193,
    "parentId": 0,
    "name": "挂号类维护",
    "url": "regClass-maintenance",
    "perms": "regClass_maintenance",
    "type": 0,
    "icon": null,
    "orderNum": 4200,
    "deleteFlag": 2,
    "syncTime": "9999-01-01",
    "menuOrgType": "HOSPITAL",
    "typeDicName": null,
    "menuOrgTypeDicName": null,
    "parentName": null,
    "open": null,
    "list": [{
        "createTime": "2020-01-03 09:43:37",
        "updateTime": "2020-01-14 16:33:30",
        "creator": "yeyi/yeyi",
        "updator": "yeyi/yeyi",
        "menuId": 19195,
        "parentId": 19193,
        "name": "挂号类别维护",
        "url": "regClass-maintenance/regClass/index",
        "perms": "register:hospitalregistertype:menu:hospital",
        "type": 1,
        "icon": null,
        "orderNum": 100,
        "deleteFlag": 2,
        "syncTime": "9999-01-01",
        "menuOrgType": "HOSPITAL",
        "typeDicName": null,
        "menuOrgTypeDicName": null,
        "parentName": null,
        "open": null,
        "list": null
    }, {
        "createTime": "2020-01-03 09:44:56",
        "updateTime": "2020-01-14 16:33:40",
        "creator": "yeyi/yeyi",
        "updator": "yeyi/yeyi",
        "menuId": 19196,
        "parentId": 19193,
        "name": "挂号诊室维护",
        "url": "regClass-maintenance/regOffice/index",
        "perms": null,
        "type": 1,
        "icon": null,
        "orderNum": 110,
        "deleteFlag": 2,
        "syncTime": "9999-01-01",
        "menuOrgType": "HOSPITAL",
        "typeDicName": null,
        "menuOrgTypeDicName": null,
        "parentName": null,
        "open": null,
        "list": null
    }, {
        "createTime": "2020-01-03 09:46:25",
        "updateTime": "2020-01-14 16:33:51",
        "creator": "yeyi/yeyi",
        "updator": "yeyi/yeyi",
        "menuId": 19197,
        "parentId": 19193,
        "name": "医生排班维护",
        "url": "regClass-maintenance/doctorSchedule/index",
        "perms": null,
        "type": 1,
        "icon": null,
        "orderNum": 120,
        "deleteFlag": 2,
        "syncTime": "9999-01-01",
        "menuOrgType": "HOSPITAL",
        "typeDicName": null,
        "menuOrgTypeDicName": null,
        "parentName": null,
        "open": null,
        "list": null
    }]
}, {
    "createTime": "2020-01-14 16:34:36",
    "updateTime": "2020-01-14 16:34:36",
    "creator": "yeyi/yeyi",
    "updator": "yeyi/yeyi",
    "menuId": 22037,
    "parentId": 0,
    "name": "挂号管理",
    "url": "registered-maintenance",
    "perms": "registered_maintenance",
    "type": 0,
    "icon": null,
    "orderNum": 4400,
    "deleteFlag": 2,
    "syncTime": "9999-01-01",
    "menuOrgType": "HOSPITAL",
    "typeDicName": null,
    "menuOrgTypeDicName": null,
    "parentName": null,
    "open": null,
    "list": [{
        "createTime": "2020-01-14 16:35:47",
        "updateTime": "2020-01-14 17:04:48",
        "creator": "yeyi/yeyi",
        "updator": "admin580/580实施人员",
        "menuId": 22038,
        "parentId": 22037,
        "name": "挂号",
        "url": "registration-maintenance/registered/index",
        "perms": "registration_maintenance",
        "type": 1,
        "icon": null,
        "orderNum": 200,
        "deleteFlag": 2,
        "syncTime": "9999-01-01",
        "menuOrgType": "HOSPITAL",
        "typeDicName": null,
        "menuOrgTypeDicName": null,
        "parentName": null,
        "open": null,
        "list": null
    }]
}, {
    "createTime": "2020-02-13 14:37:12",
    "updateTime": "2020-02-13 14:55:39",
    "creator": null,
    "updator": null,
    "menuId": 22825,
    "parentId": 0,
    "name": "门诊诊疗",
    "url": "outpatient-clinic",
    "perms": "outpatient_clinic",
    "type": 0,
    "icon": null,
    "orderNum": 4500,
    "deleteFlag": 2,
    "syncTime": "9999-01-01",
    "menuOrgType": "HOSPITAL",
    "typeDicName": null,
    "menuOrgTypeDicName": null,
    "parentName": null,
    "open": null,
    "list": [{
        "createTime": "2020-02-13 14:47:07",
        "updateTime": "2020-02-13 14:56:17",
        "creator": null,
        "updator": null,
        "menuId": 22826,
        "parentId": 22825,
        "name": "门诊医生工作站",
        "url": "outpatient-clinic/doctor-workstation/index",
        "perms": "outpatient_clinic",
        "type": 1,
        "icon": null,
        "orderNum": 0,
        "deleteFlag": 2,
        "syncTime": "9999-01-01",
        "menuOrgType": "HOSPITAL",
        "typeDicName": null,
        "menuOrgTypeDicName": null,
        "parentName": null,
        "open": null,
        "list": null
    }]
}]